import type { Metadata } from "next";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Preheader from "./components/Preheader";
import "./globals.css"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
      <div className="flex flex-col h-full w-full">
        <Preheader />
        <Header></Header>
        {children}
        <Footer />
      </div>
      </body>
    </html>
  );
}
